### ISSUE TITLE
ImportError: libavcodec.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by inzamam-iqbal** [jabelone/OpenCV-for-Pi#10]
I did exactly as you said. but when I type import cv2 it gives an error "ImportError: libavcodec.so.56: cannot open shared object file: No such file or directory"

**Comment by lewj85** [comment]
Having the same problem.

**Comment by jabelone** [comment]
Did you install *all* of the dependencies in the prior steps?

**Comment by jabelone** [comment]
The build is also a little out of date, so it could be that too. I'll try to make an updated version soon.

**Comment by kglasnapp** [comment]
I am also having the problem. I work with a bunch of student on a First Robotics Team and they would love it if you could update the build to avoid the ImportError: libavcodec.so.5 prolem. 

Thanks so much for you efforts.

**Comment by lewj85** [comment]
An update would be appreciated by our robotics team over at NYU as well!

**Comment by rbirkby** [comment]
This must be a raspbian stretch related issue. I have reverted to a fresh (most recent) jessie image and it works:

```python
>>> import cv2
>>> cv2.__version__
'3.1.0'
```

**Comment by kglasnapp** [comment]
Thank rbirkby how do you get the latest jessie image?

**Comment by rbirkby** [comment]
https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/

**Comment by kglasnapp** [comment]
Thanks -- sadly when the command 
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libv4l-dev
runs it installs libavcodec.so.57.
When the import cv2 runs it expects libavcodec.so.56
Even with the version you suggested above.

Could we somehow rebuild the latest-OpenCV.deb so it has the latest version of opencv.

Thanks so much for you efforts. I hope we can find a solution.

**Comment by rbirkby** [comment]
Strange. That was not my experience. My only deviation from the script was to install numpy with apt instead of pip.

**Comment by kglasnapp** [comment]
rbirkby -- Did you start with clean Jessie build? Did you do sudo apt-get upgrade? I wonder why yours worked and mine failed.

**Comment by rbirkby** [comment]
Yes. Burned it to an sd card. apt-get update/upgrade.

**Comment by kglasnapp** [comment]
rbirkby --  Thanks so very much. It finally worked. I do not know what I did wrong.

Keith

**Comment by AadityaRavindran** [comment]
I faced the same issue @kglasnapp 
I have the 57 version of libavcodec.

I uninstalled this version and installed opencv using this(Takes less than 5 min!) and it works like a charm:
`sudo apt-get install libopencv-dev python-opencv python-picamera`

**Comment by ghost** [comment]
hey @inzi119 did you find the solution to the problem because i m also getting same problem.

**Comment by maxisme** [comment]
I also am having this issue!

**Comment by Degeerdoethetweer** [comment]
Hi! I'm also having this issue. Has anyone managed to find a solution?

EDIT: Using an older version of Jessie solved it for me.
( https://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/ )

**Comment by iaansari** [comment]
Got it working on my Pi Zero W with Jessie. Does not work on the latest release of Raspbian "Stretch", but starting fresh with Jessie was smooth sailing.

**Comment by wbadry** [comment]
if @jabelone could recompile the latest version of OpenCV with Raspberry Stretch, this would be much appreciated.

**Comment by jabelone** [comment]
Recompiling a 3.4 version now.

**Comment by javacasm** [comment]
Sorry, but Where is the 3.4 version?

Thanks for your work!!!

**Comment by CosmaP** [comment]
Hi, I am still getting this issue.

**Comment by lukinsb** [comment]
Hello, I am still having this issue too.

**Comment by sarim987** [comment]
I am also having this issue, could you please update it?

**Comment by danarnold** [comment]
For those still having this issue, search your distro's package manager for compatibility libraries. On Arch Linux, I was able to install `ffmpeg-compat-57` and get it working.

**Comment by nathangonzalez95** [comment]
@danarnold I am new to Linux and RPi. Would you be able to give a few more details or resources on how to install ffmpeg-compat-57? Any help is much appreciated,

**Comment by danarnold** [comment]
@nathangonzales95 You need to search your distribution's package manager for a compatibility library for this older version of ffmpeg. Or, you could try downgrading your version of ffmpeg. I'm using a desktop running Arch Linux, not a raspberry pi, so I don't know anything about your system.

**Comment by Alexander-flyer** [comment]
@danarnold 
installing ffmpeg version(2.8.6) is work, thanks a lot~

**Comment by srohit0** [comment]
Installing opencv-contrib-python resolved this issue on 18.04.2 LTS (Bionic Beaver)

`pip install opencv-contrib-python`
