### ISSUE TITLE
unable to import opencv

### ISSUE THREAD

**Issue by BlcaKHat** [jabelone/OpenCV-for-Pi#11]
Python 2.7.13 (default, Jan 19 2017, 14:48:08)
[GCC 6.3.0 20170124] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libavcodec.so.56: cannot open shared object file: No such file or directory
>>> exit()

**Comment by BlcaKHat** [comment]
plz help..

**Comment by kglasnapp** [comment]
See issue #10 -- https://github.com/jabelone/OpenCV-for-Pi/issues/10 -- I was able to get it to work by starting with a clean install of jessie.  I had a bit of trouble but when I followed the instructions. I made it work. You can get jessie at 
https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/ 

Thank to rbirkby for this.  I then used the attached shell script to do the install.

[installOpenCV.txt](https://github.com/jabelone/OpenCV-for-Pi/files/1443238/installOpenCV.txt)
 
It seems to be a problem with Raspbian.

If you want you can compile the latest version OpenCV but it will take a couple of hours to get it to complete. See 

https://www.pyimagesearch.com/2017/10/09/optimizing-opencv-on-the-raspberry-pi/

It would be great if jabelone would make a new version but so far he has not.

**Comment by sanjeevcares4u** [comment]
i am not able to compile. it struct at 37 % , sometime 50%..
i am in trouble.. sombody help me out

**Comment by sanjeevcares4u** [comment]
is there any alternative to raspbian ??? that i can use in raspberry pi 3

**Comment by kglasnapp** [comment]
When you tried to compile you probably did not change the swap size. It will compile on a Raspberry PI 3.  You can change swap size with the following commands:

sudo sed -i 's/CONF_SWAPSIZE=100$/CONF_SWAPSIZE=1000/'  /etc/dphys-swapfile
 The grep command should show 1000
grep CONF_SWAPSIZE /etc/dphys-swapfile
sudo /etc/init.d/dphys-swapfile stop
sudo /etc/init.d/dphys-swapfile start

When you are finished change swap size back to 100.

If you can you can start with a clean jessie, then you do not have to compile and you can use the instructions and script from installOpenCV.txt file from above.

**Comment by haykp** [comment]
I also got the same issue. I think everyone will get the same issue as libavcodec.so.57 is newer version than libavcodec.so.56.
so to my assumption this deb file is not usable any more(((

**Comment by haykp** [comment]
Is it possible to get the copy of SD card where Jessie and opencv are already installed?

**Comment by jabelone** [comment]
This is because it's an old version and not compatible with the latest rasspbian version. I'm compiling a 3.4 version now :)

**Comment by BlcaKHat** [comment]
try installing old version. new versions have issues. mine was fine after installing an older version.
