### ISSUE TITLE
can i use this for Pi Zero W

### ISSUE THREAD

**Issue by melzoghbi** [jabelone/OpenCV-for-Pi#3]
I want to avoid the long time it is taking to build OpenCV on PI Zero W. Also, it is just changing the version will work to use OpenCV 3.2.0.

Thanks.

**Comment by jabelone** [comment]
Give it a try on the pi zero, no idea if it will work.  Theoretically, it has the same cpu architecture so I'd assume it would work.  You will have performance issues trying to run OpenCV on a pi zero though, it's very underpowered.

**Comment by melzoghbi** [comment]
I tried and it did not work. It took more than 15 hours to build and it hanged up twice! I think i need to find another route by using docker images so i can avoid the lengthy build process. still investigating..

**Comment by jabelone** [comment]
Did you follow a tutorial?  I've heard others have been successful.  Maybe start with a fresh image on the SD card and follow this tutorial.  http://www.pyimagesearch.com/2015/12/14/installing-opencv-on-your-raspberry-pi-zero/

**Comment by melzoghbi** [comment]
They used Pi 2 or 3 which is more powerful and my pi zero! the only step i get stuck on is building the OpenCV library. Other than this i was able to complete all steps till this step, but no further.
