### ISSUE TITLE
This is amazing! Can you make one for the PI Zero W?

### ISSUE THREAD

**Issue by pcriadoperez** [jabelone/OpenCV-for-Pi#4]

**Comment by jabelone** [comment]
Hey sorry forgot to reply. I don't have one so can't test it out. Just follow the same instructions and let me know if it works.

**Comment by ghost** [comment]
Pi Zero W user here - can confirm instructions in the README.md work perfectly.

Thank you! Saved me 1/2 a day!

**Comment by kglasnapp** [comment]
What version of opencv got installed?
While in python type:

`import cv2`
`cv2.__version__`

**Comment by ghost** [comment]
```
>>> cv2.__version__
'3.1.0'
```

**Comment by partha4u** [comment]
Not working in Raspbian Strech, Pi zero W
ImportError: libavcodec.so.56: cannot open shared object file: No such file or directory

**Comment by jabelone** [comment]
It seems this is the same issue of the binary being out of date. I'm compiling a new one now so will close the issue. After I've uploaded the new one open another issue if it doesn't work. :)
