### ISSUE TITLE
Please build next releases with opencv_contrib

### ISSUE THREAD

**Issue by Isstum** [jabelone/OpenCV-for-Pi#6]
Thanks for your builds, they are awesome!

But please consider to include https://github.com/opencv/opencv_contrib into your next builds.

Greetings

**Comment by jabelone** [comment]
Hey, sorry I thought I had.  That's strange.  I'm actually making a package for the newest version now and I'll be sure to definitely include the contrib package in this build.

**Comment by Isstum** [comment]
Thanks! And again: great work!

Prebuilds are a huuuge time-saver :wink: !
